### ISSUE TITLE
add suppport for latex

### ISSUE THREAD

**Issue by alvarosaurus** [alvarosaurus/Emacs_Python_R_LaTeX#5]
make sure it works with pdflatex

**Comment by AlvaroOrtizTroncoso** [comment]
Install a LaTeX distribution, e.g. on Debian, do
apt-get install texlive-full
(the Texlive distribution will use approximately 3GB of disk space).

**Comment by AlvaroOrtizTroncoso** [comment]
LaTeX works. BibTeX to go.
